device:
  name: r2
  admin_secret: "sha512 $6$eNVciFFqTEJvraTS$KpdbjnRsMVLZUdn1B9ihchnC53KQavohuceuD.L3KQWJM/h7D5MsuCd/w4y.BZfX4If76FZgCpuQ95eQFcazW1"
  vlans:
    - id: 10
      name: h1-h3
      ipv4_subnet: 11.0.0.2/24
      ipv6_subnet: 2010::2/64
      dhcp_enabled: true
      dhcp_range_start: 11.0.0.10
      dhcp_range_end: 11.0.0.50
      default_gateway: 11.0.0.3
      dhcpv6_range_start: 2010::4
      dhcpv6_range_end: 2010::ffff:ffff:fffe
      ipv4_virtual_router_address: 11.0.0.3
      ipv6_virtual_router_address: 2010::3
    - id: 20
      name: h2
      ipv4_subnet: 12.0.0.2/24
      ipv6_subnet: 2020::2/64
      dhcp_enabled: true
      dhcp_range_start: 12.0.0.10
      dhcp_range_end: 12.0.0.50
      default_gateway: 12.0.0.3
      dhcpv6_range_start: 2020::4
      dhcpv6_range_end: 2020::ffff:ffff:fffe
      ipv4_virtual_router_address: 12.0.0.3
      ipv6_virtual_router_address: 2020::3
    - id: 30
      name: h4
      ipv4_subnet: null
      ipv6_subnet: 2030::2/64
      dhcp_enabled: true
      dhcpv6_range_start: 2030::4
      dhcpv6_range_end: 2030::ffff:ffff:fffe
      ipv6_virtual_router_address: 2030::3
    - id: 50
      name: ospf
      ipv4_subnet: 100.0.0.2/29
      ipv6_subnet: 2050::/64
      dhcp_enabled: false
    - id: 100
      name: mgmt
      ipv4_subnet: 192.168.100.3/24
      ipv6_subnet: null
      dhcp_enabled: false
  interfaces:
    - name: Ethernet1
      ipv4: null
      ipv6: null
      speed: null
      switchport_mode: trunk
    - name: Ethernet2
      ipv4: null
      ipv6: null
      switchport_mode: trunk
    - name: Ethernet4
      ipv4: 192.168.101.5/24
      ipv6: null
      switchport_mode: null
    - name: Management0
      ipv4: 172.20.20.5/24
      ipv6: 2001:172:20:20::5/64
      switchport_mode: null
  routes:
    static:
      - prefix: 0.0.0.0/0
        next_hop: 172.20.20.1
      - prefix: 192.168.102.0/24
        next_hop: 192.168.101.1
      - prefix: 192.168.103.0/24
        next_hop: 192.168.101.1
    ipv6_static:
      - prefix: ::/0
        next_hop: 2001:172:20:20::1
  routing_protocols:
    ospf:
      id: 1
      networks:
        - prefix: 11.0.0.0/24
          area: 0.0.0.0
        - prefix: 12.0.0.0/24
          area: 0.0.0.0
        - prefix: 100.0.0.0/29
          area: 0.0.0.0
    rip:
      networks:
        - prefix: 11.0.0.0/24
        - prefix: 12.0.0.0/24

